package by.htp.travelserviceWEB.util;

public enum Commands {
	
	HOTEL_CATALOGUE_PAGE,
	AUTO_CATALOGUE_SORTING_PAGE,
	AUTO_SORT_SALON_PAGE,
	TOUR_CATALOGUE_PAGE,
	LOG_OUT,
	UPDATE_ACCOUNT_PAGE,
	UPDATE_ACCOUNT,
	ADMIN_PAGE,
	LOG_IN_PAGE,
	SIGN_UP_PAGE,
	LOG_IN,
	SIGN_UP;
}
